#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Task: Large Library Performance Optimization

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Task: Large Library Performance Optimization"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# VERIFY ENVIRONMENT
# ============================================

echo ""
echo -e "${BLUE}Verifying environment...${NC}"

# Check Python version
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Error: python3 not found${NC}"
    exit 1
fi

PYTHON_VERSION=$(python3 --version | cut -d' ' -f2 | cut -d'.' -f1-2)
echo "  ✓ Python version: $PYTHON_VERSION"

# Check if virtual environment exists
if [ ! -d ".venv" ]; then
    echo -e "${YELLOW}Warning: .venv not found. Creating virtual environment...${NC}"
    python3 -m venv .venv
fi

# Activate virtual environment
source .venv/bin/activate

# Install dependencies
echo ""
echo -e "${BLUE}Installing dependencies...${NC}"
pip install -q -e ".[web,search,dedup]"
echo "  ✓ Dependencies installed"

# Check Redis (optional for caching)
if command -v redis-cli &> /dev/null; then
    if redis-cli ping &> /dev/null; then
        echo "  ✓ Redis available"
    else
        echo -e "${YELLOW}  ⚠ Redis not running (optional for caching)${NC}"
    fi
else
    echo -e "${YELLOW}  ⚠ Redis not installed (optional for caching)${NC}"
fi

# ============================================
# DATABASE SETUP
# ============================================

echo ""
echo -e "${BLUE}Setting up database...${NC}"

# Run Alembic migrations
if [ -d "alembic" ]; then
    echo "  Running database migrations..."
    alembic upgrade head
    echo "  ✓ Database migrations applied"
else
    echo -e "${YELLOW}  ⚠ No alembic directory found${NC}"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo -e "${BLUE}Starting services...${NC}"

# Backend API (FastAPI)
echo "  Starting FastAPI backend on port 8000..."
uvicorn file_organizer.api.main:app --reload --port 8000 &
BACKEND_PID=$!
wait_for_service 8000 "FastAPI Backend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API:  http://localhost:8000"
echo "  API Docs:     http://localhost:8000/docs"
echo "  Web UI:       http://localhost:8000/ui/"
echo ""
echo "PIDs:"
echo "  Backend: $BACKEND_PID"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID"
echo ""
echo "Next steps:"
echo "  1. Review implementation_plan.json"
echo "  2. Run baseline benchmarks:"
echo "     python benchmarks/file_scanning_benchmark.py"
echo "     python benchmarks/search_benchmark.py"
echo "     python benchmarks/dedup_benchmark.py"
echo ""
echo "  3. Start implementing subtasks in order"
echo ""
echo "========================================"
