"""Canonical destination adapters for organization methodologies.

The standalone PARA and Johnny Decimal packages contain the vocabulary and
folder/numbering primitives. This module is the single bridge from processed
organization results into those packages; presentation layers must select a
methodology through :class:`OrganizeOptions` instead of remapping plans.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import replace
from pathlib import Path

from file_organizer.core.organize_options import OrganizationMethodology
from file_organizer.methodologies.johnny_decimal.categories import (
    AreaDefinition,
    JohnnyDecimalNumber,
    get_default_scheme,
)
from file_organizer.methodologies.para.categories import PARACategory
from file_organizer.methodologies.para.folder_generator import PARAFolderGenerator
from file_organizer.services import ProcessedFile, ProcessedImage

ProcessedResult = ProcessedFile | ProcessedImage

_PARA_SOURCE_NAMES: dict[str, PARACategory] = {
    "project": PARACategory.PROJECT,
    "projects": PARACategory.PROJECT,
    "area": PARACategory.AREA,
    "areas": PARACategory.AREA,
    "resource": PARACategory.RESOURCE,
    "resources": PARACategory.RESOURCE,
    "archive": PARACategory.ARCHIVE,
    "archives": PARACategory.ARCHIVE,
}


def apply_organization_methodology(
    processed: Iterable[ProcessedResult],
    *,
    input_root: Path,
    methodology: OrganizationMethodology,
) -> list[ProcessedResult]:
    """Return processed results routed through the selected methodology."""
    results = list(processed)
    if methodology == OrganizationMethodology.NONE:
        return results

    remapped: list[ProcessedResult] = []
    for result in results:
        if methodology == OrganizationMethodology.PARA:
            folder = _para_destination(result, input_root)
        else:
            folder = _johnny_decimal_destination(result, input_root)
        remapped.append(replace(result, folder_name=folder))
    return remapped


def _para_destination(result: ProcessedResult, input_root: Path) -> str:
    """Map one result using canonical PARA category primitives."""
    existing = _safe_folder(result.folder_name)
    existing_parts = Path(existing).parts
    if existing_parts:
        existing_category = _PARA_SOURCE_NAMES.get(existing_parts[0].casefold())
        if existing_category is not None:
            canonical_root = _para_root(existing_category)
            return Path(canonical_root, *existing_parts[1:]).as_posix()

    category = _source_para_category(result.file_path, input_root)
    canonical_root = _para_root(category)
    return (Path(canonical_root) / existing).as_posix()


def _source_para_category(source: Path, input_root: Path) -> PARACategory:
    """Infer a PARA category from source ancestors, defaulting to Resources."""
    try:
        parent_parts = source.relative_to(input_root).parts[:-1]
    except ValueError:
        parent_parts = source.parts[:-1]
    for part in parent_parts:
        category = _PARA_SOURCE_NAMES.get(part.casefold())
        if category is not None:
            return category
    return PARACategory.RESOURCE


def _para_root(category: PARACategory) -> str:
    """Return the canonical root folder generated by the PARA package."""
    generator = PARAFolderGenerator()
    return generator.get_category_path(category, Path()).as_posix()


def _johnny_decimal_destination(result: ProcessedResult, input_root: Path) -> str:
    """Map one result into the existing default Johnny Decimal scheme."""
    existing = _safe_folder(result.folder_name)
    existing_parts = Path(existing).parts
    first_part = existing_parts[0] if existing_parts else ""
    if _has_johnny_decimal_prefix(first_part):
        return existing

    try:
        relative_source = result.file_path.relative_to(input_root).as_posix()
    except ValueError:
        relative_source = result.file_path.name
    searchable = f"{relative_source} {existing} {result.filename}".casefold()
    area = _select_johnny_decimal_area(searchable)
    number = JohnnyDecimalNumber(area=area.area_range_start, category=1)
    area_folder = f"{area.area_range_start:02d} {area.name}"
    category_folder = f"{number.formatted_number} {existing}"
    return (Path(area_folder) / category_folder).as_posix()


def _select_johnny_decimal_area(searchable: str) -> AreaDefinition:
    """Select the best matching area from the default Johnny Decimal scheme."""
    scheme = get_default_scheme()
    unique_areas = {definition.area_range_start: definition for definition in scheme.areas.values()}
    scored = [
        (
            sum(1 for keyword in definition.keywords if keyword.casefold() in searchable),
            -definition.area_range_start,
            definition,
        )
        for definition in unique_areas.values()
    ]
    matches, _, selected = max(scored, key=lambda item: (item[0], item[1]))
    if matches:
        return selected
    # Preserve the former dashboard's honest default for uncategorized input.
    fallback = scheme.get_area(30)
    if fallback is None:  # pragma: no cover - invariant of the default scheme
        raise RuntimeError("Default Johnny Decimal scheme has no operations area")
    return fallback


def _has_johnny_decimal_prefix(folder: str) -> bool:
    """Return whether a folder already starts with a Johnny Decimal number."""
    if len(folder) < 2 or not folder[:2].isdigit():
        return False
    return len(folder) == 2 or folder[2] in {" ", "."}


def _safe_folder(folder: str) -> str:
    """Return a safe relative classifier folder or the Unsorted fallback."""
    candidate = Path(folder)
    if candidate.is_absolute() or not candidate.parts or ".." in candidate.parts:
        return "Unsorted"
    return candidate.as_posix()
