from typing import Any

class EdDSASigScheme:
    def sign(self, msg_or_hash: Any) -> bytes: ...
    def verify(self, msg_or_hash: Any, signature: Any) -> None: ...

def new(key: Any, mode: Any, context: Any = ...) -> EdDSASigScheme: ...
