from typing import Any

bool: Any

class ndarray:
    T: ndarray
    shape: tuple[int, ...]
    def __iter__(self) -> Any: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __truediv__(self, other: Any) -> ndarray: ...
    def __mul__(self, other: Any) -> ndarray: ...
    def tolist(self) -> list[Any]: ...

def array(object: Any, dtype: Any = ..., *args: Any, **kwargs: Any) -> ndarray: ...
def asarray(a: Any, dtype: Any = ..., *args: Any, **kwargs: Any) -> ndarray: ...
def argsort(a: Any, *args: Any, **kwargs: Any) -> ndarray: ...
def dot(a: Any, b: Any, *args: Any, **kwargs: Any) -> Any: ...
def clip(a: Any, a_min: Any, a_max: Any, *args: Any, **kwargs: Any) -> Any: ...
def eye(N: int, M: int | None = ..., k: int = ..., dtype: Any = ..., *args: Any, **kwargs: Any) -> ndarray: ...
def mean(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def median(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def std(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def max(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def min(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def sum(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def save(file: Any, arr: Any, *args: Any, **kwargs: Any) -> None: ...
def load(file: Any, *args: Any, **kwargs: Any) -> ndarray: ...
