#!/usr/bin/env python3
"""Generate the canonical Markdown capability matrix from registry state.

This script parses file_organizer.core.capabilities.get_capability_registry()
and generates docs/developer/capability-matrix.md deterministically.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

# Ensure src/ is on Python path when run directly
_ROOT = Path(__file__).resolve().parent.parent
_SRC = _ROOT / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from file_organizer.core.capabilities import (
    Capability,
    ConformanceStatus,
    ExecutionScope,
    ImplementationStatus,
    SupportLevel,
    Surface,
    get_capability_registry,
)

DEFAULT_OUTPUT_PATH = Path("docs/developer/capability-matrix.md")

_SURFACE_DISPLAY_NAMES: dict[Surface, str] = {
    Surface.CLI: "CLI",
    Surface.REST_API: "REST API",
    Surface.PYTHON_SDK: "Python SDK",
    Surface.TYPESCRIPT_SDK: "TypeScript SDK",
    Surface.WEB_DESKTOP: "Web / Desktop",
    Surface.TUI: "TUI",
}


def _format_surface_cell(status) -> str:
    """Format one matrix cell with explicit target, implementation, and verification."""
    if status.target_support is SupportLevel.NOT_APPLICABLE:
        return "N/A"

    target_str = status.target_support.value.capitalize()
    impl_str = status.implementation_status.value.capitalize()
    conf_str = status.conformance_status.value.capitalize()
    return f"{target_str} ({impl_str} / {conf_str})"


def generate_capability_matrix_markdown() -> str:
    """Generate deterministic Markdown representing the canonical capability matrix."""
    registry = get_capability_registry()
    lines: list[str] = []

    lines.append("<!-- Generated by scripts/generate_capability_matrix.py. DO NOT EDIT. -->")
    lines.append("# Product Capability Matrix")
    lines.append("")
    lines.append(
        "This document is automatically generated from `src/file_organizer/core/capability_registry.json`. "
        "It provides an authoritative, evidence-backed matrix of product capabilities across all official surfaces."
    )
    lines.append("")
    lines.append("## Status Dimensions")
    lines.append("")
    lines.append(
        "- **Target Support**: Intended product support level (`Full`, `Read-only`, `Redirect/deep-link`, `N/A`)."
    )
    lines.append(
        "- **Implementation Status**: Current implementation state (`Implemented`, `Partial`, `Not-implemented`, `N/A`)."
    )
    lines.append(
        "- **Conformance Status**: Executable parity evidence state (`Verified`, `Unverified`, `N/A`)."
    )
    lines.append("")
    lines.append(
        "> [!IMPORTANT]\n"
        "> A surface cell formatted as `Full (Implemented / Unverified)` represents an implemented feature that lacks full executable conformance evidence. "
        "Target support is never equated with verified shipped status."
    )
    lines.append("")

    # Summary Statistics
    lines.append("## Summary Statistics")
    lines.append("")
    lines.append(f"**Total Capabilities**: {len(registry.capabilities)}")
    lines.append("")
    lines.append("| Surface | Target Full/Read-Only | Implemented | Conformance Verified |")
    lines.append("|---|---|---|---|")

    for surface in Surface:
        target_count = sum(
            1
            for cap in registry.capabilities
            if cap.support_for(surface).target_support
            in (SupportLevel.FULL, SupportLevel.READ_ONLY)
        )
        impl_count = sum(
            1
            for cap in registry.capabilities
            if cap.support_for(surface).implementation_status
            in (ImplementationStatus.IMPLEMENTED, ImplementationStatus.PARTIAL)
        )
        conf_count = sum(
            1
            for cap in registry.capabilities
            if cap.support_for(surface).conformance_status is ConformanceStatus.VERIFIED
        )
        display_name = _SURFACE_DISPLAY_NAMES[surface]
        lines.append(f"| {display_name} | {target_count} | {impl_count} | {conf_count} |")

    lines.append("")

    # Main Matrix Table
    lines.append("## Cross-Surface Overview Matrix")
    lines.append("")
    lines.append(
        "| Capability ID | Name | Maturity | CLI | REST API | Python SDK | TypeScript SDK | Web / Desktop | TUI |"
    )
    lines.append("|---|---|---|---|---|---|---|---|---|")

    for cap in registry.capabilities:
        cli_cell = _format_surface_cell(cap.support_for(Surface.CLI))
        rest_cell = _format_surface_cell(cap.support_for(Surface.REST_API))
        py_cell = _format_surface_cell(cap.support_for(Surface.PYTHON_SDK))
        ts_cell = _format_surface_cell(cap.support_for(Surface.TYPESCRIPT_SDK))
        web_cell = _format_surface_cell(cap.support_for(Surface.WEB_DESKTOP))
        tui_cell = _format_surface_cell(cap.support_for(Surface.TUI))

        lines.append(
            f"| [`{cap.capability_id}`](#{cap.capability_id.replace('.', '')}) | {cap.name} | {cap.maturity.value.capitalize()} | "
            f"{cli_cell} | {rest_cell} | {py_cell} | {ts_cell} | {web_cell} | {tui_cell} |"
        )

    lines.append("")
    lines.append("## Detailed Capability Breakdown")
    lines.append("")

    for cap in registry.capabilities:
        anchor_id = cap.capability_id.replace(".", "")
        lines.append(f'<a id="{anchor_id}"></a>')
        lines.append(f"### `{cap.capability_id}` — {cap.name}")
        lines.append("")
        lines.append(f"**Description**: {cap.description}")
        lines.append("")
        lines.append(f"- **Maturity**: {cap.maturity.value.capitalize()}")
        scopes_str = ", ".join(f"`{scope.value}`" for scope in cap.execution_scopes)
        lines.append(f"- **Execution Scopes**: {scopes_str}")
        platforms_str = ", ".join(f"`{p.value}`" for p in cap.platforms)
        lines.append(f"- **Platforms**: {platforms_str}")
        deps_str = (
            ", ".join(f"`{dep}`" for dep in cap.optional_dependencies)
            if cap.optional_dependencies
            else "None"
        )
        lines.append(f"- **Optional Dependencies**: {deps_str}")
        lines.append("")
        lines.append("#### Surface Status & Entry Points")
        lines.append("")
        lines.append("| Surface | Target Support | Implementation | Conformance | Entry Points |")
        lines.append("|---|---|---|---|---|")

        for surface in Surface:
            status = cap.support_for(surface)
            disp = _SURFACE_DISPLAY_NAMES[surface]
            target = status.target_support.value.capitalize()
            impl = status.implementation_status.value.capitalize()
            conf = status.conformance_status.value.capitalize()
            entries = (
                ", ".join(f"`{e}`" for e in status.entry_points) if status.entry_points else "None"
            )
            lines.append(f"| {disp} | {target} | {impl} | {conf} | {entries} |")

        lines.append("")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate canonical Markdown capability matrix from registry state."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="Target output path for capability matrix (default: docs/developer/capability-matrix.md)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check if target capability matrix file is up to date without writing.",
    )
    args = parser.parse_args(argv)

    generated_content = generate_capability_matrix_markdown()
    target_path = args.output

    if args.check:
        if not target_path.exists():
            print(f"ERROR: Capability matrix file '{target_path}' does not exist.", file=sys.stderr)
            return 1
        existing_content = target_path.read_text(encoding="utf-8")
        if existing_content != generated_content:
            print(
                f"ERROR: Capability matrix in '{target_path}' is out of date.",
                file=sys.stderr,
            )
            diff = difflib.unified_diff(
                existing_content.splitlines(keepends=True),
                generated_content.splitlines(keepends=True),
                fromfile=str(target_path),
                tofile="generated",
            )
            sys.stderr.writelines(diff)
            print(
                "\nRun 'python scripts/generate_capability_matrix.py' to update it.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: Capability matrix in '{target_path}' is up to date.")
        return 0

    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(generated_content, encoding="utf-8")
    print(f"Successfully wrote capability matrix to '{target_path}'.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
