name: Lint Markdown

on: [push, pull_request]

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
      - uses: actions/setup-python@f677139bbe7f9c59b41e7cf4bdfca50c6605f8fe  # v5.2.1
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install pymarkdown
        run: pip install 'pymarkdownlnt>=0.9.25'
      - name: Run markdown linting
        run: pymarkdown -c .pymarkdown.json scan docs/ README.md *.md
